### ISSUE TITLE
Can't get quotes

### ISSUE THREAD

**Issue by GiganteX** [lzehrung/coinmarketcap#6]
Hi!

I could get the map ID's for my currencies, no problem.

But when I tried this:
			var response = AsyncHelper.RunSync(() =>
				client.GetLatestQuoteAsync(new LatestQuoteParameters { Id = 1027 }, CancellationToken.None));

...which should get me the quote for Ethereum (id 1027) but I get nothing... see attached screenshot..

What's wrong?
![Capture](https://user-images.githubusercontent.com/15637533/104654852-18370a00-56bd-11eb-9689-203ab334412d.PNG)

**Comment by SamJongenelen** [comment]
Same issue here; ` GetCryptocurrencyIdMapAsync`  works fine, but `GetLatestQuoteAsync` results in an succeeded request, but with an empty response object. 
CMC change the response contract?
